### PR TITLE
Send logged addresses to stdout

### PR DESCRIPTION
**Pull request by martriay**
For programmatic usage.

### CODE REVIEW

**Comment by frangio** [comment]
This is introducing a lot of duplicate output... I'm not sure it's the right approach. Have we considered command line flags to trigger verbose logging?

**Comment by martriay** [comment]
@frangio verbose logging it's being added in https://github.com/zeppelinos/zos-cli/pull/97, in the meantime I think that duplicated output is an acceptable solution.

**Comment by spalladino** [comment]
-1 to automatically outputting addresses to stdout. We want to control what we output in each case in that it must be useful to the user, instead of just throwing everything that looks pipeable. As for duplicating info, I think it's best for now: stderr tells you what's going on, while stdout outputs composable data.

**Comment by facuspagnuolo** [comment]
I didn’t mean to output it automatically, could be controled by a flag. -1 to force logging twice. 

Another option is to have another function in `Logger` that receives two messages,  one for stderr and another for stdout, if you don’t like the idea of parsing the messag

**Comment by frangio** [comment]
By the way, Truffle does not guarantee that the `"address"` field that some of this logs are using begins with `0x`. We may want to do something about that.

**Comment by facuspagnuolo** [comment]
Then I'll go with adding a new `info` method that can receive stderr and stdout messages

**Comment by spalladino** [comment]
I suggest we do the following:
- Remove all `log.out` calls from lib
- Have lib return addresses (or objects with addresses)
- Call log.out from CLI at the end of each `script` (when appropriate)

This would remove pipeable calls from lib (which doesn't make sense to be in lib), and ensure that duplicated output is not intermixed, but stdout is printed at the very end. WDYT?

**Comment by frangio** [comment]
YES. That is the only thing that makes sense, now that I think of it.

**Comment by spalladino** [comment]
@martriay can you tackle this?

**Pull request closed without merging**
